parameter_defaults:
  # Generally the IP of the Undercloud
  #EC2MetadataIp: 192.168.25.1

  DnsServers: ["10.46.0.31","10.46.0.32"]
  NeutronNetworkType: 'vlan,flat'
  NeutronTunnelTypes: ''
  NeutronBridgeMappings: 'datacentre:br-ext-int'
  NeutronNetworkVLANRanges: 'datacentre:319:319,datacentre:321:324,datacentre:354:368'
  OvercloudControlFlavor: controller
  OvercloudComputeSriovFlavor: compute
  NeutronEnableDVR: false

  ControllerSriovSchedulerHints:
    'capabilities:node': 'controller-%index%'
  ComputeSriovSchedulerHints:
    'capabilities:node': 'compute-%index%'

  # Internal QE setting, might not be suitable for production deployments.
  # Set root password on overcloud nodes
  #NodeRootPassword: '12345678'

  #### Extras ####
  NovaPCIPassthrough:
    - devname: "enp7s0f3"
      trusted: "true"
      physical_network: "datacentre"
    - devname: "enp5s0f0"
      trusted: "true"
      physical_network: "datacentre"

  NovaSchedulerDefaultFilters: ['AvailabilityZoneFilter','ComputeFilter','ComputeCapabilitiesFilter','DifferentHostFilter', 'ImagePropertiesFilter','ServerGroupAntiAffinityFilter','ServerGroupAffinityFilter','PciPassthroughFilter']
  NovaSchedulerAvailableFilters: ["nova.scheduler.filters.all_filters","nova.scheduler.filters.pci_passthrough_filter.PciPassthroughFilter"]
  NeutronPhysicalDevMappings: "datacentre:enp7s0f3,datacentre:enp5s0f0"
  NeutronSupportedPCIVendorDevs: ['8086:154c', '8086:1572']
  NeutronSriovNumVFs: ["enp7s0f3:5", "enp5s0f0:5"]
  NeutronDebug: True
  ComputeSriovParameters:
    KernelArgs: "default_hugepagesz=1GB hugepagesz=1G hugepages=32 iommu=pt intel_iommu=on"
    TunedProfileName: "cpu-partitioning"
    IsolCpusList: "2-23"
    NovaReservedHostMemory: 4096

  ###add placement service plugin###
  NeutronServicePlugins: 'qos,ovn-router,trunk,segments,placement'
  NeutronSriovResourceProviderBandwidths: 'enp7s0f3:10000000:10000000,enp5s0f0:10000000:10000000'
  NeutronSriovAgentExtensions: 'qos'
  ExtraConfig:
    neutron::agents::ml2::sriov::resource_provider_hypervisors: "enp7s0f3:%{hiera('fqdn_canonical')},enp5s0f0:%{hiera('fqdn_canonical')}"

  ComputeSriovNetworkConfigTemplate: "/home/stack/ospd-17-vlan-sriov-hybrid-ha-ovn-squad-titan09/nic-configs/compute.yaml"
  ControllerSriovNetworkConfigTemplate: "/home/stack/ospd-17-vlan-sriov-hybrid-ha-ovn-squad-titan09/nic-configs/controller.yaml"

