resource_registry:
  OS::TripleO::Controller0::Net::SoftwareConfig: spine-leaf-nics/controller0.yaml
  OS::TripleO::Compute2::Net::SoftwareConfig: spine-leaf-nics/compute2.yaml
  OS::TripleO::Services::Docker: OS::Heat::None
  OS::TripleO::Services::NovaAZConfig: /usr/share/openstack-tripleo-heat-templates/deployment/nova/nova-az-config.yaml
  OS::TripleO::Network::Ports::RedisVipPort: /usr/share/openstack-tripleo-heat-templates/network/ports/noop.yaml
  OS::TripleO::Network::Ports::OVNDBsVipPort: /usr/share/openstack-tripleo-heat-templates/network/ports/noop.yaml

parameter_defaults:
  NeutronEnableIsolatedMetadata: 'True'
  ControlPlaneSubnet: leaf0
  VipSubnetMap:
    ctlplane: leaf0
  NeutronFlatNetworks: leaf0,leaf2
  Controller0Parameters:
    NeutronBridgeMappings: ["leaf0:br-ex"]
  Compute2Parameters:
    NeutronBridgeMappings: ["leaf2:br-ex"]
  PythonInterpreter: /usr/bin/python3
  NovaComputeLibvirtType: qemu
  DnsServers: ['10.11.5.19', '10.5.30.160']
  NtpServer: ["clock.redhat.com","clock2.redhat.com"]
  NovaComputeAvailabilityZone: az-dcn2
  NeutronL3AgentAvailabilityZone: az-dcn2
  NeutronDhcpAgentAvailabilityZone: az-dcn2
  NeutronMechanismDrivers: 'openvswitch'
  NeutronRouterSchedulerDriver: 'neutron.scheduler.l3_agent_scheduler.AZLeastRoutersScheduler'
  NeutronNetworkSchedulerDriver: 'neutron.scheduler.dhcp_agent_scheduler.AZAwareWeightScheduler'
  NeutronDhcpLoadType: 'networks'
  NovaCrossAZAttach: False
  RootStackName: dcn2
  ManageNetworks: False
  NeutronEnableDVR: 'false'
  NeutronExternalNetworkBridge: ''
  NeutronNetworkType: 'vxlan'
  NeutronTunnelTypes: 'vxlan'
  NeutronNetworkVLANRanges: 'leaf0:1:1000,leaf2:1:1000'
  BondInterfaceOvsOptions: "bond_mode=active-backup"

  ExternalNetCidr: '10.0.10.0/24'
  ExternalAllocationPools: [{'start': '10.0.10.150', 'end': '10.0.10.169'}]
  ExternalInterfaceDefaultRoute: '10.0.10.1'
  ExternalNetworkVlanID: 10

  StorageNetCidr: '172.23.1.0/24'
  StorageAllocationPools: [{'start': '172.23.1.4', 'end': '172.23.1.250'}]
  StorageInterfaceDefaultRoute: '172.23.1.254'
  StorageNetworkVlanID: 1183

  StorageSubnetCidr_storage_leaf2: '172.23.3.0/24'
  StorageAllocationPools_storage_leaf2: [{'start': '172.23.3.4', 'end': '172.23.3.250'}]
  StorageInterfaceDefaultRoute_storage_leaf2: '172.23.3.254'
  StorageNetworkVlanID_storage_leaf2: 1163

  StorageMgmtNetCidr: '172.18.1.0/24'
  StorageMgmtAllocationPools: [{'start': '172.18.1.4', 'end': '172.18.1.250'}]
  StorageMgmtInterfaceDefaultRoute: '172.18.1.254'
  StorageMgmtNetworkVlanID: 1188

  StorageMgmtSubnetCidr_storage_mgmt_leaf2: '172.18.3.0/24'
  StorageMgmtAllocationPools_storage_mgmt_leaf2: [{'start': '172.18.3.4', 'end': '172.18.3.250'}]
  StorageMgmtInterfaceDefaultRoute_storage_mgmt_leaf2: '172.18.3.254'
  StorageMgmtNetworkVlanID_storage_mgmt_leaf2: 1168

  InternalApiNetCidr: '172.25.1.0/24'
  InternalApiAllocationPools: [{'start': '172.25.1.4', 'end': '172.25.1.250'}]
  InternalApiInterfaceDefaultRoute: '172.25.1.254'
  InternalApiNetworkVlanID: 1185

  InternalApiSubnetCidr_internal_api_leaf2: '172.25.3.0/24'
  InternalApiAllocationPools_internal_api_leaf2: [{'start': '172.25.3.4', 'end': '172.25.3.250'}]
  InternalApiInterfaceDefaultRoute_internal_api_leaf2: '172.25.3.254'
  InternalApiNetworkVlanID_internal_api_leaf2: 1165

  TenantNetCidr: '172.19.1.0/24'
  TenantAllocationPools: [{'start': '172.19.1.4', 'end': '172.19.1.250'}]
  TenantInterfaceDefaultRoute: '172.19.1.254'
  TenantNetworkVlanID: 1189
  TenantNetPhysnetMtu: 1500

  TenantSubnetCidr_tenant_leaf2: '172.19.3.0/24'
  TenantAllocationPools_tenant_leaf2: [{'start': '172.19.3.4', 'end': '172.19.3.250'}]
  TenantInterfaceDefaultRoute_tenant_leaf2: '172.19.3.254'
  TenantNetworkVlanID_tenant_leaf2: 1169
