resource_registry:
  OS::TripleO::ComputeSriov::NodeUserData: /usr/share/openstack-tripleo-heat-templates/firstboot/os-net-config-mappings.yaml

parameter_defaults:
  NetConfigDataLookup:
    overcloud-controller0-0:
      nic1: "ens3"
      nic2: "ens4"
      nic3: "ens5"
    overcloud-controller0-1:
      nic1: "ens3"
      nic2: "ens4"
      nic3: "ens5"
    overcloud-controller0-2:
      nic1: "ens3"
      nic2: "ens4"
      nic3: "ens5"
    control0:
      nic1: "ens3"
      nic2: "ens4"
      nic3: "ens5"
