- name: Controller
  count: 3
  hostname_format: controller-%index%
  defaults:
    profile: control
    networks:
      - network: external
        subnet: external_subnet
      - network: internal_api
        subnet: internal_api_subnet
      - network: storage
        subnet: storage_subnet
      - network: storage_mgmt
        subnet: storage_mgmt_subnet
      - network: tenant
        subnet: tenant_subnet
    network_config:
      template: /home/stack/vlan_provider_network_ovn/OSP17/nic-configs/controller.yaml
      default_route_network:
        - external
  ansible_playbooks:
    - playbook: /usr/share/ansible/tripleo-playbooks/cli-overcloud-node-growvols.yaml
      extra_vars:
        growvols_args: >
          /=8GB
          /tmp=1GB
          /var/log=3GB
          /var/log/audit=1GB
          /home=1GB
          /srv=10GB
          /var=100%

- name: Networker
  count: 3
  hostname_format: networker-%index%
  defaults:
    profile: networker
    networks:
      - network: external
        subnet: external_subnet
      - network: internal_api
        subnet: internal_api_subnet
      - network: storage
        subnet: storage_subnet
      - network: tenant
        subnet: tenant_subnet
    network_config:
      template: /home/stack/vlan_provider_network_ovn/OSP17/nic-configs/networker.yaml
      default_route_network:
        - external
  ansible_playbooks:
    - playbook: /usr/share/ansible/tripleo-playbooks/cli-overcloud-node-growvols.yaml
      extra_vars:
        growvols_args: >
          /=8GB
          /tmp=1GB
          /var/log=3GB
          /var/log/audit=1GB
          /home=1GB
          /srv=10GB
          /var=100%

- name: Compute
  count: 2
  hostname_format: compute-%index%
  defaults:
    profile: compute
    networks:
      - network: internal_api
        subnet: internal_api_subnet
      - network: tenant
        subnet: tenant_subnet
      - network: storage
        subnet: storage_subnet
    network_config:
      template: /home/stack/vlan_provider_network_ovn/OSP17/nic-configs/compute.yaml
    config_drive:
      cloud_config:
        ssh_pwauth: true
        disable_root: false
        chpasswd:
          list: |-
            root:12345678
          expire: False
