---
parameter_defaults:
    NeutronNetworkType: ['geneve','vlan']
    NeutronNetworkVLANRanges: leaf0:500:600,leaf1:601:700,leaf2:701:800
    NeutronTunnelTypes: 'geneve,vlan'
    NeutronTypeDrivers: 'geneve,vlan'
