parameter_defaults:
  #Enable isolated metadata for provider networks
  NeutronEnableIsolatedMetadata: 'True'
  # Generally the IP of the Undercloud
  #EC2MetadataIp: 192.168.25.1

  DnsServers: ["10.46.0.31","10.46.0.32"]
  NeutronExternalNetworkBridge: "''"
  NeutronNetworkType: 'vlan,flat'
  #OVNTunnelEncapType: 'vlan'
  NeutronTunnelTypes: ''
  NeutronBridgeMappings: 'datacentre:br-ext-int'
  NeutronNetworkVLANRanges: 'datacentre:411:411,datacentre:412:434'
  OvercloudControlFlavor: controller
  OvercloudComputeSriovFlavor: compute
  NeutronEnableDVR: false

 # Number of nodes to deploy.
  ControllerCount: 3
  ComputeSriovCount: 2
  NtpServer: clock.redhat.com

 # Ironic mapping
  ControllerHostnameFormat: 'controller-%index%'
  ControllerSchedulerHints:
    'capabilities:node': 'controller-%index%'
  ComputeSriovHostnameFormat: 'computesriov-%index%'
  ComputeSriovSchedulerHints:
    'capabilities:node': 'compute-%index%'


#### Extras ####
  NeutronMechanismDrivers: ['sriovnicswitch', 'openvswitch']
  #NeutronMechanismDrivers: "ovn,sriovnicswitch"
  NovaPCIPassthrough:
    - devname: "enp6s0f3"
      trusted: "true"
      physical_network: "datacentre"

  NovaSchedulerAvailableFilters: ["nova.scheduler.filters.all_filters","nova.scheduler.filters.pci_passthrough_filter.PciPassthroughFilter"]
  NovaSchedulerDefaultFilters: ['AvailabilityZoneFilter','ComputeFilter','ComputeCapabilitiesFilter','ImagePropertiesFilter','ServerGroupAntiAffinityFilter','ServerGroupAffinityFilter','PciPassthroughFilter']
  NeutronPhysicalDevMappings: "datacentre:enp6s0f3"
  NeutronSupportedPCIVendorDevs: ['8086:1572']
  NeutronSriovNumVFs: ["enp6s0f3:5"]
  ComputeSriovParameters:
    KernelArgs: "default_hugepagesz=1GB hugepagesz=1G hugepages=32 iommu=pt intel_iommu=on"
    TunedProfileName: "cpu-partitioning"
    IsolCpusList: "2-23"
    NovaReservedHostMemory: 4096

  ComputeSriovNetworkConfigTemplate: "/home/stack/ospd-17-vlan-sriov-hybrid-ha-ovs-squad-titan13/nic-configs/compute.yaml"
  ControllerSriovNetworkConfigTemplate: "/home/stack/ospd-17-vlan-sriov-hybrid-ha-ovs-squad-titan13/nic-configs/controller.yaml"

