resource_registry:
  # Specify the relative/absolute path to the config files you want to use for override the default.
  OS::TripleO::ComputeSriov::Net::SoftwareConfig: nic-configs/compute.yaml
  OS::TripleO::ComputeSriov1::Net::SoftwareConfig: nic-configs/compute.yaml
  OS::TripleO::Controller::Net::SoftwareConfig: nic-configs/controller.yaml
parameter_defaults:
  #Enable isolated metadata for provider networks
  NeutronEnableIsolatedMetadata: 'True'
  # Customize all these values to match the local environment
  InternalApiNetCidr: 10.20.1.0/24
  TenantNetCidr: 10.20.2.0/24
  TenantNetCidr_external_leaf: 10.20.5.0/24
  StorageNetCidr: 10.20.3.0/24
  StorageMgmtNetCidr: 10.20.4.0/24
  ExternalNetCidr: 10.46.54.0/26

 # CIDR subnet mask length for provisioning network
  ControlPlaneSubnetCidr: '24'
  InternalApiAllocationPools: [{'start': '10.20.1.61', 'end': '10.20.1.80'}]
  TenantAllocationPools_external_leaf: [{'start': '10.20.5.61', 'end': '10.20.5.80'}]
  TenantAllocationPools: [{'start': '10.20.2.61', 'end': '10.20.2.80'}]
  StorageAllocationPools: [{'start': '10.20.3.61', 'end': '10.20.3.80'}]
  StorageMgmtAllocationPools: [{'start': '10.20.4.61', 'end': '10.20.4.80'}]

  # Use an External allocation pool which will leave room for floating IPs
  ExternalAllocationPools: [{'start': '10.46.54.2', 'end': '10.46.54.21'}]
  ExternalAllocationPools_external_leaf: [{'start': '10.46.54.66', 'end': '10.46.54.85'}]
  # Set to the router gateway on the external network
  ExternalInterfaceDefaultRoute: 10.46.54.62
  ExternalInterfaceDefaultRoute_external_leaf: 10.46.54.126

  # Gateway router for the provisioning network (or Undercloud IP)
  ControlPlaneDefaultRoute: 192.168.25.1
  # Generally the IP of the Undercloud
  EC2MetadataIp: 192.168.25.1

  InternalApiNetworkVlanID: 280
  TenantNetworkVlanID: 410
  TenantNetworkVlanID_external_leaf: 411
  StorageNetworkVlanID: 282
  StorageMgmtNetworkVlanID: 283

  ExternalNetworkVlanID: 408
  ExternalNetworkVlanID_external_leaf: 409

  DnsServers: ["10.46.0.31","10.46.0.32"]
  NeutronExternalNetworkBridge: "''"
  NeutronNetworkType: 'vlan,flat'
  #OVNTunnelEncapType: 'vlan'
  NeutronTunnelTypes: ''
  ControllerParameters:
    NeutronBridgeMappings:
    - datacentre:br-ext-int
    - tenant:br-int
  #NeutronBridgeMappings: 'datacentre:br-ext-int,tenant:br-int'
  NeutronFlatNetworks: 'leaf,datacentre'
  NeutronNetworkVLANRanges: 'datacentre:408:408,datacentre:412:434,leaf:409:409,leaf:412:434'
  OvercloudControlFlavor: controller
  OvercloudComputeSriovFlavor: compute
  OvercloudComputeSriov1Flavor: compute
  NeutronEnableDVR: false

 # Number of nodes to deploy.
  ControllerCount: 3
  ComputeSriovCount: 1
  ComputeSriov1Count: 1
  NtpServer: clock.redhat.com

 # Ironic mapping
  ControllerHostnameFormat: 'controller-%index%'
  ControllerSchedulerHints:
    'capabilities:node': 'controller-%index%'
  ComputeSriovHostnameFormat: 'computesriov-%index%'
  ComputeSriov1HostnameFormat: 'computesriov1-%index%'
  ComputeSriovSchedulerHints:
    'capabilities:node': 'compute-%index%'
  ComputeSriov1SchedulerHints:
    'capabilities:node': 'compute1-%index%'


#### Extras ####
  NeutronMechanismDrivers: ['sriovnicswitch', 'openvswitch']
  #NeutronMechanismDrivers: "ovn,sriovnicswitch"

  NovaSchedulerAvailableFilters: ["nova.scheduler.filters.all_filters","nova.scheduler.filters.pci_passthrough_filter.PciPassthroughFilter"]
  NovaSchedulerDefaultFilters: ['AvailabilityZoneFilter','ComputeFilter','ComputeCapabilitiesFilter','ImagePropertiesFilter','ServerGroupAntiAffinityFilter','ServerGroupAffinityFilter','PciPassthroughFilter']
  NeutronSupportedPCIVendorDevs: ['8086:1572']
  NeutronSriovNumVFs: ["enp6s0f3:5"]
  ComputeSriovParameters:
    KernelArgs: "default_hugepagesz=1GB hugepagesz=1G hugepages=32 iommu=pt intel_iommu=on"
    TunedProfileName: "cpu-partitioning"
    IsolCpusList: "2-23"
    NovaReservedHostMemory: 4096
    NeutronPhysicalDevMappings: 
    - datacentre:enp6s0f3
    NeutronBridgeMappings:
    - datacentre:br-ext-int
    - tenant:br-int
    NovaPCIPassthrough:
      - devname: "enp6s0f3"
        physical_network: "datacentre"
        trusted: "true"

  ComputeSriov1Parameters:
    KernelArgs: "default_hugepagesz=1GB hugepagesz=1G hugepages=32 iommu=pt intel_iommu=on"
    TunedProfileName: "cpu-partitioning"
    IsolCpusList: "2-23"
    NovaReservedHostMemory: 4096
    NeutronPhysicalDevMappings: 
    - leaf:enp6s0f3
    NeutronBridgeMappings:
    - leaf:br-ext-int
    - tenant-leaf:br-int
    NovaPCIPassthrough:
      - devname: "enp6s0f3"
        physical_network: "datacentre"
        trusted: "true"
