- name : Create temp file directory if not present
  file:
    state: directory
    path: "{{ ovn_migration_temp_dir }}"

- name: Generate resource creation script
  template:
    src: create-resources.sh.j2
    dest: "{{ ovn_migration_temp_dir }}/create-resources.sh"
    mode: 0744

- name: Creating pre pre migration resources
  shell: >
    set -o pipefail &&
    {{ ovn_migration_temp_dir }}/create-resources.sh >
    {{ ovn_migration_temp_dir }}/create-resources.sh.log 2>&1
  changed_when: true

- name: Generate prepare-pinger script
  template:
    src: prepare-pinger.sh.j2
    dest: "{{ ovn_migration_temp_dir }}/prepare-pinger.sh"
    mode: 0744

- name: Generate start-pinger script
  template:
    src: start-pinger.sh.j2
    dest: "{{ ovn_migration_temp_dir }}/start-pinger.sh"
    mode: 0744

- name: Generate requester script
  template:
    src: start-requester.sh.j2
    dest: "{{ ovn_migration_temp_dir }}/start-requester.sh"
    mode: 0744
  when: loadbalancer|bool

- name: Generate pinger validation script
  template:
    src: validate-pinger.sh.j2
    dest: "{{ ovn_migration_temp_dir }}/validate-pinger.sh"
    mode: 0744

- name: Execute prepare-pinger script
  shell: >
      {{ ovn_migration_temp_dir }}/prepare-pinger.sh </dev/null >
      {{ ovn_migration_temp_dir }}/prepare-pinger.sh.log 2>&1
  changed_when: False
  when: not shutdown_workload|bool

- name: Start pinger in background
  shell: >
      nohup {{ ovn_migration_temp_dir }}/start-pinger.sh </dev/null >/dev/null 2>&1 &
  changed_when: False
  when: not shutdown_workload|bool

- name: Start requester in background
  shell: >
      nohup {{ ovn_migration_temp_dir }}/start-requester.sh </dev/null >/dev/null 2>&1 &
  changed_when: False
  when:
      - loadbalancer|bool
      - not shutdown_workload|bool

- name: Create network validate script
  template:
    src: validate-network.sh.j2
    dest: "{{ ovn_migration_working_dir }}/validate-network.sh"
    mode: 0744

- name: Create load balancer validation script
  template:
    src: validate-loadbalancer.sh.j2
    dest: "{{ ovn_migration_working_dir }}/validate-loadbalancer.sh"
    mode: 0744
  when: loadbalancer|bool
