---
net_port: false
image: false
keypair: false
security_group: false
# Set tempest to test provider networks connectivity
enable_test_all_provider_networks: true

networks:
  - name: 'datacentre'
    physical_network: 'datacentre'
    segmentation_id: '319'
    allocation_pool_start: '10.46.21.193'
    allocation_pool_end: '10.46.21.212'
    cidr: '10.46.21.192/26'
    enable_dhcp: true
    gateway_ip: '10.46.21.254'
    external: true
    shared: true
    router_name: router1
    port_type: normal
    network_type: vlan
    ip_version: 4

test-networks:
  - name: 'normal-mgmt'
    physical_network: 'datacentre'
    allocation_pool_start: '10.10.10.100'
    allocation_pool_end: '10.10.10.200'
    cidr: '10.10.10.0/24'
    enable_dhcp: true
    gateway_ip: '10.10.10.254'
    network_type: vlan
    ip_version: 4
    sec_groups: true
    port_type: normal
    mgmt: true
    tag: external
    dns_nameservers:
      - 10.46.0.31
      - 8.8.8.8

  - name: 'sriov-1'
    allocation_pool_start: '40.0.0.100'
    allocation_pool_end: '40.0.0.200'
    physical_network: datacentre
    cidr: '40.0.0.0/24'
    enable_dhcp: false
    gateway_ip: '40.0.0.254'
    network_type: vlan
    ip_version: 4
    sec_groups: true
    port_type: direct
    trusted_vf: true

  - name: 'sriov-2'
    allocation_pool_start: '50.0.0.100'
    allocation_pool_end: '50.0.0.200'
    physical_network: datacentre
    cidr: '50.0.0.0/24'
    enable_dhcp: false
    gateway_ip: '50.0.0.254'
    network_type: vlan
    ip_version: 4
    sec_groups: true
    port_type: direct

dns_nameservers:
  - 10.46.0.31
  - 8.8.8.8

flavors:
  - name: nfv_qe_base_flavor
    ram: 8192
    disk: 20
    vcpus: 6
    extra_specs:
      "hw:mem_page_size": "large"
      "hw:cpu_policy": "dedicated"
      "hw:emulator_threads_policy": "share"

images:
- name: rhel7.6
  url: https://url.corp.redhat.com/rhel-guest-image-7-6-210-x86-64-qcow2

image_ssh_user: cloud-user
tempest_flavor_name: nfv_qe_base_flavor

tests_regex: '^nfv_tempest_plugin(.*basic)(.*cold_migration)'

# The section below currently is a requirement.
# Will be removed soon, as part of an ongoing refactoring.
tests-setup:
 - name: dump_string
