resource_registry:
  OS::TripleO::ComputeSriov::NodeUserData: /usr/share/openstack-tripleo-heat-templates/firstboot/os-net-config-mappings.yaml

parameter_defaults:
  NetConfigDataLookup:
    computesriov1:
      dmiString: "system-uuid"
      id: "4c4c4544-0047-3410-8059-c4c04f395132"
      nic1: "enp7s0f0"
      nic2: "enp7s0f1"
      nic3: "enp7s0f2"
      nic4: "enp7s0f3"
      nic5: "enp5s0f0"

    computesriov0:
      dmiString: "system-uuid"
      id: "4c4c4544-0047-3310-8059-c4c04f395132"
      nic1: "enp7s0f0"
      nic2: "enp7s0f1"
      nic3: "enp7s0f2"
      nic4: "enp7s0f3"
      nic5: "enp5s0f0"
