resource_registry:
  OS::TripleO::ComputeSriov::NodeUserData: /usr/share/openstack-tripleo-heat-templates/firstboot/os-net-config-mappings.yaml

parameter_defaults:
  NetConfigDataLookup:
    computesriovgroup:
      dmiString: "system-product-name"
      id: "PowerEdge C6220"
      nic1: "eno1" # In biosdevname "em1"
      nic2: "eno2" # In biosdevname "em2"
      nic3: "enp5s0f0" # In biosdevname "p1p1"
      nic4: "enp5s0f1" # In biosdevname "p1p2"
